stages:
    - build
    - lint
    - test

variables:
    RULES_CHANGES_PATH: "**/*"

.base-rules:
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          when: always
        - if: '$CI_PIPELINE_SOURCE == "push"'
          when: never
        - if: $CI_COMMIT_TAG
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          changes:
              - $RULES_CHANGES_PATH
        - when: manual
          allow_failure: true

.api:
    extends: .base-rules
    variables:
        RULES_CHANGES_PATH: "api/**/*"

api-build:
    tags:
        - node
    stage: build
    extends: .api
    needs: []
    before_script:
        - cd api
        - npm install
    script:
        - npm run build

api-lint:
    tags:
        - node
    stage: lint
    extends: .api
    needs: ["api-build"]
    before_script:
        - cd api
        - npm install
    script:
        - npm run lint

api-test:
    tags:
        - node
    stage: test
    extends: .api
    before_script:
        - cd api
        - npm install
    needs: ["api-build"]
    script:
        - npm run test
