stages:
    - deploy

variables:
    APP_NAME: decision

deploy:
    image: ilyasemenov/gitlab-ci-git-push
    stage: deploy
    environment:
        name: production
        url: https://$APP_NAME.projects.multimedia.at
    only:
        - master
    script:
        - cd app
        - git-push ssh://dokku@projects.multimedia.at:5412/decision.me:22/$APP_NAME
