const data = [
    {
        fsq_id: "4e9352d729c27df469033fa1",
        categories: [
            { id: 13064, name: "Pizzeria", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/pizza_", suffix: ".png" } },
            { id: 13236, name: "Italian Restaurant", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/italian_", suffix: ".png" } },
        ],
        chains: [],
        distance: 192,
        geocodes: { main: { latitude: 47.807757, longitude: 13.05523 }, roof: { latitude: 47.807757, longitude: 13.05523 } },
        location: {
            address: "Vogelweiderstraße 9",
            country: "AT",
            cross_street: "",
            formatted_address: "Vogelweiderstraße 9, 5020 Salzburg",
            locality: "Salzburg",
            neighborhood: ["Schallmoos"],
            postcode: "5020",
            region: "Salzburg",
        },
        name: "Bella Vita Pizzeria Ristorante",
        related_places: {},
        timezone: "Europe/Vienna",
    },
    {
        fsq_id: "5ac5173067e5f21e366e4924",
        categories: [{ id: 13272, name: "Ramen Restaurant", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/ramen_", suffix: ".png" } }],
        chains: [],
        distance: 171,
        geocodes: { main: { latitude: 47.80923, longitude: 13.057304 }, roof: { latitude: 47.80923, longitude: 13.057304 } },
        location: {
            address: "Sterneckstraße 33",
            country: "AT",
            cross_street: "",
            formatted_address: "Sterneckstraße 33, 5020 Salzburg",
            locality: "Salzburg",
            postcode: "5020",
            region: "Salzburg",
        },
        name: "Ichi Go Ichi E Ramen Bar",
        related_places: {},
        timezone: "Europe/Vienna",
    },
    {
        fsq_id: "5613fcf4498e6c88c8dc96c0",
        categories: [
            { id: 13068, name: "American Restaurant", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/default_", suffix: ".png" } },
        ],
        chains: [],
        distance: 169,
        geocodes: { main: { latitude: 47.809363, longitude: 13.056858 }, roof: { latitude: 47.809363, longitude: 13.056858 } },
        location: {
            address: "Sterneckstraße 31- 33",
            country: "AT",
            cross_street: "",
            formatted_address: "Sterneckstraße 31- 33, 5020 Salzburg",
            locality: "Salzburg",
            postcode: "5020",
            region: "Salzburg",
        },
        name: "Susie´s American Diner",
        related_places: {},
        timezone: "Europe/Vienna",
    },
    {
        fsq_id: "4ba3a7a9f964a5209d5038e3",
        categories: [{ id: 13057, name: "Gastropub", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/gastropub_", suffix: ".png" } }],
        chains: [],
        distance: 386,
        geocodes: { main: { latitude: 47.806172, longitude: 13.053539 } },
        location: {
            address: "",
            country: "AT",
            cross_street: "",
            formatted_address: "Salzburg",
            locality: "Salzburg",
            postcode: "",
            region: "Salzburg",
        },
        name: "Kastner's Schenke",
        related_places: {},
        timezone: "Europe/Vienna",
    },
    {
        fsq_id: "4bcb4cea68f976b048c66083",
        categories: [
            { id: 13030, name: "Buffet", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/default_", suffix: ".png" } },
            { id: 13352, name: "Thai Restaurant", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/thai_", suffix: ".png" } },
        ],
        chains: [],
        distance: 420,
        geocodes: { main: { latitude: 47.807492, longitude: 13.05951 }, roof: { latitude: 47.807492, longitude: 13.05951 } },
        location: {
            address: "Schallmooser Hauptstraße 71",
            country: "AT",
            formatted_address: "Schallmooser Hauptstraße 71, 5020 Salzburg",
            locality: "Salzburg",
            neighborhood: ["Schallmoos"],
            postcode: "5020",
            region: "Salzburg",
        },
        name: "Lek's Thai Küche",
        related_places: {},
        timezone: "Europe/Vienna",
    },
    {
        fsq_id: "4eb6bd459adfc68712f2bd8c",
        categories: [
            { id: 13025, name: "Wine Bar", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/winery_", suffix: ".png" } },
            { id: 13057, name: "Gastropub", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/gastropub_", suffix: ".png" } },
            { id: 13074, name: "Austrian Restaurant", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/austrian_", suffix: ".png" } },
        ],
        chains: [],
        distance: 485,
        geocodes: { main: { latitude: 47.807251, longitude: 13.060786 }, roof: { latitude: 47.807251, longitude: 13.060786 } },
        location: {
            address: "Schallmooser Hauptstraße 50",
            country: "AT",
            cross_street: "",
            formatted_address: "Schallmooser Hauptstraße 50, 5020 Salzburg",
            locality: "Salzburg",
            neighborhood: ["Schallmoos"],
            postcode: "5020",
            region: "Salzburg",
        },
        name: "Urbankeller",
        related_places: {},
        timezone: "Europe/Vienna",
    },
    {
        fsq_id: "56d17ff3cd10ad699c355405",
        categories: [{ id: 13031, name: "Burger Joint", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/burger_", suffix: ".png" } }],
        chains: [],
        distance: 860,
        geocodes: { main: { latitude: 47.80415, longitude: 13.046626 }, roof: { latitude: 47.80415, longitude: 13.046626 } },
        location: {
            address: "Linzer Gasse 39",
            country: "AT",
            cross_street: "Bruderhof",
            formatted_address: "Linzer Gasse 39 (Bruderhof), 5020 Salzburg",
            locality: "Salzburg",
            postcode: "5020",
            region: "Salzburg",
        },
        name: "Ludwig",
        related_places: {},
        timezone: "Europe/Vienna",
    },
    {
        fsq_id: "4ed8bc0e0e61d46ad5ec1038",
        categories: [{ id: 13177, name: "Greek Restaurant", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/greek_", suffix: ".png" } }],
        chains: [],
        distance: 781,
        geocodes: { main: { latitude: 47.808664, longitude: 13.065286 }, roof: { latitude: 47.808664, longitude: 13.065286 } },
        location: {
            address: "Fürbergstraße 18- 20",
            country: "AT",
            cross_street: "",
            formatted_address: "Fürbergstraße 18- 20, 5020 Salzburg",
            locality: "Salzburg",
            postcode: "5020",
            region: "Salzburg",
        },
        name: "Akropolis",
        related_places: {},
        timezone: "Europe/Vienna",
    },
    {
        fsq_id: "4bf56ad86a31d13a96da962e",
        categories: [
            {
                id: 13377,
                name: "Vegan and Vegetarian Restaurant",
                icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/vegetarian_", suffix: ".png" },
            },
        ],
        chains: [],
        distance: 980,
        geocodes: { main: { latitude: 47.809834, longitude: 13.041474 }, roof: { latitude: 47.809834, longitude: 13.041474 } },
        location: {
            address: "Elisabethstraße 1",
            country: "AT",
            cross_street: "",
            formatted_address: "Elisabethstraße 1, 5020 Salzburg",
            locality: "Salzburg",
            neighborhood: ["Froscheim"],
            postcode: "5020",
            region: "Salzburg",
        },
        name: "Leichtsinn - Vitalbistro",
        related_places: {},
        timezone: "Europe/Vienna",
    },
    {
        fsq_id: "5594ddd2498eac3395ae3db1",
        categories: [{ id: 13034, name: "Café", icon: { prefix: "https://ss3.4sqi.net/img/categories_v2/food/cafe_", suffix: ".png" } }],
        chains: [],
        distance: 856,
        geocodes: { main: { latitude: 47.804124, longitude: 13.047063 }, roof: { latitude: 47.804124, longitude: 13.047063 } },
        location: {
            address: "Bruderhof",
            country: "AT",
            cross_street: "",
            formatted_address: "Bruderhof, Salzburg",
            locality: "Salzburg",
            postcode: "",
            region: "Salzburg",
        },
        name: "Coffee House Bruderhof",
        related_places: {},
        timezone: "Europe/Vienna",
    },
];

export default data;
